### ISSUE TITLE
Openjdk11

### ISSUE THREAD

**Issue by tuxark** [j-tim/docker-maven-non-root#1]
Hi Tim, thanks for your work.

Do you think you're doing a version for openjdk 11?

Regards,

Jeremy

**Comment by j-tim** [comment]
Hi @tuxark sorry for my late response.
I recommend you to take a look at my docker build image project: https://github.com/j-tim/docker-docker-compose-jdk-mvn that one has support for Adapt OpenJdk 11.

See also the Docker images on dockerhub:  https://hub.docker.com/r/jtim/docker-docker-compose-jdk-mvn
